name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

#      - name: Deploy to Ubuntu server via SSH
#        if: success()
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          host: 288478-web-01
#          username: ubuntu
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: 22
#          script: |
#            cd /path/to/your/app || exit
#            git pull origin main
#            # If you need to install/update dependencies:
#            source venv/bin/activate
#            pip install -r requirements.txt
#            # Restart your app (example with systemd)
#            sudo systemctl restart your-app.service